/* Speusis Extension — Content Script v0.29 - removed hover-to-reveal gating on YouTube, always shows once detected again (matches v0.21's reliable behavior), kept v0.28's player-anchored positioning */
/* Intercepts downloadable links, detects HLS/DASH/video streams on any page */
"use strict";

const DOWNLOADABLE = /\.(7z|apk|avi|bin|bz2|csv|deb|dmg|doc|docx|exe|flac|flv|gz|img|iso|jar|mkv|mov|mp3|mp4|msi|ogg|pdf|pkg|rar|rpm|tar|ts|wav|webm|wmv|xls|xlsx|xz|zip)(\?|#|$)/i;
const STREAM_EXTS  = /\.(m3u8|mpd|m4s)(\?|#|$)/i;
const YOUTUBE_VIDEO_PATH = /^(\/watch|\/shorts\/|\/live\/)/;

/* Chrome may restart the MV3 service worker between detection and click.
 * Always consume the callback error so the content script does not surface
 * "message port closed" as an uncaught extension error. */
function sendRuntimeMessage(message) {
  try {
    chrome.runtime.sendMessage(message, () => {
      void chrome.runtime.lastError;
    });
  } catch {}
}

function isYouTubeVideoPage() {
  return location.hostname.includes("youtube.com") &&
    YOUTUBE_VIDEO_PATH.test(location.pathname);
}

/* ── Badge settings (persisted in storage) ──────────────────────── */
let _badgeTheme   = "dark";
let _badgeOpacity = 0.88;
let _badgeHidden  = false;
let _badgeCollapsed = false;
let _badgeDragged = false;

chrome.storage.local.get(["speusis_badge_theme", "speusis_badge_opacity"], (res) => {
  if (res.speusis_badge_theme)   _badgeTheme   = res.speusis_badge_theme;
  if (res.speusis_badge_opacity) _badgeOpacity = parseFloat(res.speusis_badge_opacity);
});

function saveBadgeSettings() {
  chrome.storage.local.set({
    speusis_badge_theme:   _badgeTheme,
    speusis_badge_opacity: _badgeOpacity,
  });
}

/* ── Detected stream URLs ───────────────────────────────────────── */
const detectedStreams = new Map();
let streamBadgeEl    = null;
let videoObserver    = null;

/* ── YouTube adaptive-format pools (v0.23) ──────────────────────────
 * Combined (progressive) itags still go straight into detectedStreams,
 * unchanged from before. Adaptive video-only / audio-only itags land
 * here first, keyed by itag, as they're actually requested by the real
 * player. Once at least one video itag AND one audio itag have been
 * captured, they're paired into a "needs mux" entry in detectedStreams —
 * two URLs the desktop app downloads and merges into one file. */
const ytAdaptiveVideo = new Map(); // itag -> {itag, quality, url}
const ytAdaptiveAudio = new Map(); // itag -> {itag, quality, url}
const ytPendingFormats = new Map(); // itag -> {itag, quality, kind, pending}
let ytCurrentVideoId = "";
let ytKnownFormatCount = 0;        // from the full player-response scan, for the "+N more" hint
let ytLockedFormatCount = 0;

function pickBestAudio() {
  // Prefer higher-bitrate AAC/Opus if more than one audio itag got captured.
  const RANK = { "141": 0, "251": 1, "140": 2, "250": 3, "139": 4, "249": 5 };
  let best = null;
  for (const a of ytAdaptiveAudio.values()) {
    if (!best || (RANK[a.itag] ?? 9) < (RANK[best.itag] ?? 9)) best = a;
  }
  return best;
}

function rebuildYouTubeMuxPairs() {
  const audio = pickBestAudio();
  for (const v of ytAdaptiveVideo.values()) {
    const key = `yt-mux-${v.itag}`;
    if (audio) {
      detectedStreams.set(key, {
        url: v.url,           // representative URL (used for display/ranking)
        videoUrl: v.url,
        audioUrl: audio.url,
        needsMux: true,
        type: "MP4",
        quality: `${v.quality} (muxed)`,
        // Approximate: video-only stream size dominates the final muxed
        // file, so this is close enough for display purposes even though
        // the audio track adds a bit more.
        fileSize: (v.fileSize && audio.fileSize) ? v.fileSize + audio.fileSize : (v.fileSize || null),
        timestamp: Date.now(),
      });
      ytPendingFormats.delete(String(v.itag));
    } else {
      /* Keep every discovered resolution visible while the audio request is
       * still in flight.  The old code dropped video-only formats here,
       * leaving only the one progressive stream that arrived first. */
      ytPendingFormats.set(String(v.itag), {
        itag: String(v.itag),
        quality: v.quality,
        type: "MP4",
        pending: true,
        kind: "video",
        timestamp: Date.now(),
      });
    }
  }
  if (audio || ytAdaptiveVideo.size) updateStreamBadge();
}

function recordYouTubeSubtitle(sub) {
  if (!isYouTubeVideoPage()) return;
  const key = `yt-sub-${sub.lang}`;
  if (detectedStreams.has(key)) return;
  detectedStreams.set(key, {
    url: sub.url,
    type: "Subtitle",
    quality: `${sub.label || sub.lang}${sub.autoGenerated ? " (auto)" : ""}`,
    timestamp: Date.now(),
  });
  updateStreamBadge();
}

/* ── Theme tokens ───────────────────────────────────────────────── */
function themeVars(theme, opacity) {
  const isDark = theme === "dark";
  return {
    bg:         isDark ? `rgba(10,12,22,${opacity})`       : `rgba(245,246,252,${opacity})`,
    bgHeader:   isDark ? `rgba(18,20,36,${opacity})`       : `rgba(235,237,248,${opacity})`,
    bgList:     isDark ? `rgba(8,10,20,${opacity * 0.9})`  : `rgba(252,252,255,${opacity * 0.9})`,
    bgItem:     isDark ? `rgba(30,35,60,0.55)`              : `rgba(220,224,245,0.55)`,
    bgDlBtn:    isDark ? `rgba(60,80,180,0.85)`             : `rgba(50,80,200,0.9)`,
    bgDlBtnHov: isDark ? `rgba(80,100,210,0.95)`            : `rgba(40,65,180,0.95)`,
    bgDownAll:  isDark ? `rgba(20,24,50,${opacity * 0.8})` : `rgba(228,232,252,${opacity * 0.8})`,
    border:     isDark ? `rgba(120,130,200,0.18)`           : `rgba(80,90,180,0.18)`,
    borderItem: isDark ? `rgba(60,70,140,0.25)`             : `rgba(100,110,200,0.18)`,
    text:       isDark ? `rgba(220,224,245,0.95)`           : `rgba(22,24,48,0.92)`,
    textMuted:  isDark ? `rgba(140,150,200,0.75)`           : `rgba(80,88,140,0.75)`,
    textAll:    isDark ? `rgba(140,170,255,0.9)`            : `rgba(40,60,180,0.9)`,
    mainBtn:    isDark ? `rgba(28,32,60,0.0)`               : `rgba(230,234,252,0.0)`,
    mainBtnHov: isDark ? `rgba(40,50,100,0.5)`              : `rgba(200,210,240,0.6)`,
    menuBg:     isDark ? `rgba(14,16,32,0.97)`              : `rgba(245,246,255,0.98)`,
    menuBorder: isDark ? `rgba(100,110,200,0.22)`           : `rgba(80,90,180,0.22)`,
    sliderTrack:isDark ? `rgba(80,90,180,0.4)`              : `rgba(80,90,200,0.3)`,
    scrollBar:  isDark ? `rgba(80,90,180,0.35)`             : `rgba(100,110,200,0.3)`,
    tagBg:      isDark ? `rgba(40,60,180,0.75)`             : `rgba(50,80,200,0.75)`,
  };
}

/* ── CSS (structure only — colors applied via JS vars) ─────────── */
const BADGE_CSS = `
  #__speusis-stream-badge {
    position: fixed;
    top: 12px;
    right: 12px;
    z-index: 2147483647;
    border-radius: 12px;
    font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
    font-size: 12px;
    min-width: 270px;
    max-width: 360px;
    overflow: visible;
    user-select: none;
    -webkit-font-smoothing: antialiased;
    transition: opacity 0.2s;
  }
  /* v0.28 fix: when anchored inside YouTube's own player container
     (#movie_player, which YouTube itself keeps position:relative for
     its own control overlays), absolute-inside-parent instead of
     fixed-to-viewport - this is what actually anchors the badge to the
     player the way IDM's does, and what makes it move naturally with
     scroll/theater-mode/fullscreen without any extra JS tracking. */
  #__speusis-stream-badge.__speusis-yt-anchored {
    position: absolute;
    top: 8px;
    right: 8px;
  }
  #__speusis-stream-badge * { box-sizing: border-box; }

  .__speusis-badge-wrap {
    border-radius: 12px;
    overflow: hidden;
    backdrop-filter: blur(20px) saturate(200%);
    -webkit-backdrop-filter: blur(20px) saturate(200%);
  }

  .__speusis-badge-header {
    display: flex;
    align-items: stretch;
    gap: 0;
  }
  .__speusis-drag-handle {
    width: 24px;
    border: none;
    border-right: 1px solid transparent;
    background: transparent;
    color: inherit;
    opacity: .5;
    cursor: grab;
    touch-action: none;
    font-size: 13px;
    letter-spacing: -3px;
    padding: 0 7px;
  }
  .__speusis-drag-handle:active { cursor: grabbing; }
  .__speusis-badge-main-btn {
    display: flex;
    align-items: center;
    gap: 7px;
    flex: 1;
    padding: 7px 9px;
    background: transparent;
    border: none;
    cursor: pointer;
    font-weight: 700;
    font-size: 11.5px;
    font-family: inherit;
    text-align: left;
    transition: background 0.15s;
    border-radius: 0;
  }
  .__speusis-badge-icon { width: 15px; height: 15px; flex-shrink: 0; opacity: 0.9; }

  .__speusis-badge-dots-btn {
    background: none;
    border: none;
    cursor: pointer;
    font-size: 17px;
    padding: 0 8px;
    line-height: 1;
    letter-spacing: 0;
    display: flex;
    align-items: center;
    opacity: 0.55;
    transition: opacity 0.15s, background 0.15s;
    font-family: inherit;
    position: relative;
    border-left: 1px solid transparent;
  }
  .__speusis-collapse-btn {
    display: grid;
    place-items: center;
    background: transparent;
    border: none;
    border-left: 1px solid transparent;
    color: inherit;
    cursor: pointer;
    width: 30px;
    min-height: 30px;
    padding: 0;
    opacity: .72;
    transition: opacity 0.14s, background 0.14s;
  }
  .__speusis-collapse-btn:hover { opacity: 1; background: rgba(120,140,255,0.14); }
  .__speusis-collapse-icon {
    width: 14px;
    height: 14px;
    transition: transform 0.16s cubic-bezier(.22,.8,.3,1);
  }
  #__speusis-stream-badge.__speusis-collapsed .__speusis-collapse-icon {
    transform: rotate(180deg);
  }
  .__speusis-badge-dots-btn:hover { opacity: 1; }

  .__speusis-badge-download-all {
    display: flex;
    align-items: center;
    padding: 5px 12px;
    cursor: pointer;
    font-size: 11px;
    font-weight: 600;
    transition: background 0.12s;
    border-top: 1px solid transparent;
    border-bottom: 1px solid transparent;
  }

  .__speusis-badge-content {
    max-height: 210px;
    overflow: hidden;
    opacity: 1;
    transform: translateY(0);
    transition:
      max-height 0.16s cubic-bezier(.22,.8,.3,1),
      opacity 0.11s ease,
      transform 0.16s cubic-bezier(.22,.8,.3,1);
  }
  #__speusis-stream-badge.__speusis-collapsed .__speusis-badge-content {
    max-height: 0;
    opacity: 0;
    transform: translateY(-5px);
    pointer-events: none;
  }
  .__speusis-collapsed-actions {
    display: flex;
    max-height: 0;
    overflow: hidden;
    opacity: 0;
    padding: 0 6px;
    transform: translateY(-4px);
    pointer-events: none;
    transition:
      max-height 0.16s cubic-bezier(.22,.8,.3,1),
      opacity 0.11s ease,
      transform 0.16s cubic-bezier(.22,.8,.3,1),
      padding 0.16s cubic-bezier(.22,.8,.3,1);
  }
  #__speusis-stream-badge.__speusis-collapsed .__speusis-collapsed-actions {
    max-height: 44px;
    opacity: 1;
    padding: 6px;
    transform: translateY(0);
    pointer-events: auto;
  }
  .__speusis-auto-btn {
    width: 100%;
    border: none;
    border-radius: 6px;
    padding: 6px 8px;
    color: #fff;
    cursor: pointer;
    font: 700 11px "Segoe UI", system-ui, sans-serif;
  }
  .__speusis-badge-list {
    max-height: 160px;
    overflow-y: auto;
  }
  .__speusis-badge-list::-webkit-scrollbar { width: 4px; }
  .__speusis-badge-list::-webkit-scrollbar-track { background: transparent; }

  .__speusis-badge-item {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 12px;
    cursor: pointer;
    transition: background 0.12s;
    border-bottom: 1px solid transparent;
  }
  .__speusis-badge-num { font-size: 10px; min-width: 14px; flex-shrink: 0; }
  .__speusis-badge-item-info {
    flex: 1;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    font-size: 11px;
  }
  .__speusis-badge-type-tag {
    border-radius: 4px;
    padding: 1px 6px;
    font-size: 9px;
    font-weight: 800;
    color: #fff;
    flex-shrink: 0;
    letter-spacing: .04em;
  }
  .__speusis-badge-dl-btn {
    border: none;
    color: #fff;
    border-radius: 5px;
    padding: 3px 9px;
    cursor: pointer;
    font-size: 11px;
    font-weight: 700;
    flex-shrink: 0;
    font-family: inherit;
    transition: background 0.15s;
  }

  /* ── Settings dropdown ──
     NOTE: Rendered as a direct child of #__speusis-stream-badge (position:fixed)
     so it escapes the overflow:hidden on .__speusis-badge-wrap            ── */
  .__speusis-settings-menu {
    position: absolute;
    top: 44px;
    right: 0;
    z-index: 2147483648;
    border-radius: 10px;
    width: 220px;
    padding: 12px;
    backdrop-filter: blur(24px) saturate(200%);
    -webkit-backdrop-filter: blur(24px) saturate(200%);
    box-shadow: 0 8px 32px rgba(0,0,0,0.32), 0 2px 8px rgba(0,0,0,0.16);
    display: none;
  }
  .__speusis-settings-menu.open { display: block; }
  .__speusis-menu-label {
    font-size: 10px;
    font-weight: 700;
    letter-spacing: .07em;
    text-transform: uppercase;
    margin-bottom: 7px;
    opacity: 0.6;
  }
  .__speusis-theme-row {
    display: flex;
    gap: 6px;
    margin-bottom: 12px;
  }
  .__speusis-theme-btn {
    flex: 1;
    border: 1px solid transparent;
    border-radius: 6px;
    padding: 5px 0;
    font-size: 11px;
    font-weight: 700;
    cursor: pointer;
    font-family: inherit;
    transition: all 0.15s;
    opacity: 0.6;
  }
  .__speusis-theme-btn.active { opacity: 1; }
  .__speusis-opacity-row { margin-bottom: 12px; }
  .__speusis-opacity-slider {
    width: 100%;
    -webkit-appearance: none;
    height: 3px;
    border-radius: 3px;
    outline: none;
    cursor: pointer;
    margin-top: 8px;
  }
  .__speusis-opacity-slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 14px;
    height: 14px;
    border-radius: 50%;
    background: #6080ff;
    cursor: pointer;
    box-shadow: 0 1px 4px rgba(0,0,0,0.3);
  }
  .__speusis-divider { height: 1px; margin: 8px -12px 10px; opacity: 0.15; }
  .__speusis-hide-btn {
    width: 100%;
    border: none;
    border-radius: 7px;
    padding: 7px 0;
    font-size: 11.5px;
    font-weight: 600;
    cursor: pointer;
    font-family: inherit;
    opacity: 0.75;
    transition: opacity 0.15s;
    background: rgba(220,50,50,0.12);
    color: #e05050;
  }
  .__speusis-hide-btn:hover { opacity: 1; background: rgba(220,50,50,0.2); }
`;

function injectBadgeStyles() {
  if (document.getElementById("__speusis-badge-styles")) return;
  const style = document.createElement("style");
  style.id = "__speusis-badge-styles";
  style.textContent = BADGE_CSS;
  (document.head || document.documentElement).appendChild(style);
}

/* ── Apply theme colors to a rendered badge ─────────────────────── */
function applyTheme(root, theme, opacity) {
  const t = themeVars(theme, opacity);
  const wrap     = root.querySelector(".__speusis-badge-wrap");
  const header   = root.querySelector(".__speusis-badge-header");
  const dragHandle = root.querySelector(".__speusis-drag-handle");
  const mainBtn  = root.querySelector(".__speusis-badge-main-btn");
  const dotsBtn  = root.querySelector(".__speusis-badge-dots-btn");
  const collapseBtn = root.querySelector(".__speusis-collapse-btn");
  const autoBtn  = root.querySelector(".__speusis-auto-btn");
  const dlAll    = root.querySelector(".__speusis-badge-download-all");
  const list     = root.querySelector(".__speusis-badge-list");
  const menu     = root.querySelector(".__speusis-settings-menu");

  if (wrap)   { wrap.style.background = t.bg; wrap.style.border = `1px solid ${t.border}`; wrap.style.boxShadow = `0 8px 32px rgba(0,0,0,0.25), 0 2px 8px rgba(0,0,0,0.12)`; }
  if (header) { header.style.background = t.bgHeader; header.style.borderBottom = `1px solid ${t.border}`; }
  if (dragHandle) { dragHandle.style.color = t.text; dragHandle.style.borderRightColor = t.border; }
  if (mainBtn){ mainBtn.style.color = t.text; }
  if (dotsBtn){ dotsBtn.style.color = t.text; dotsBtn.style.borderLeftColor = t.border; }
  if (collapseBtn) { collapseBtn.style.color = t.text; collapseBtn.style.borderLeftColor = t.border; }
  if (autoBtn) { autoBtn.style.background = t.bgDlBtn; }
  if (dlAll)  { dlAll.style.background = t.bgDownAll; dlAll.style.color = t.textAll; dlAll.style.borderColor = t.border; }
  if (list)   {
    list.style.background = t.bgList;
    list.querySelectorAll("::-webkit-scrollbar-thumb");
  }

  root.querySelectorAll(".__speusis-badge-item").forEach(item => {
    item.style.borderBottomColor = t.borderItem;
    item.style.color = t.text;
    item._speusisColors = t;
  });
  root.querySelectorAll(".__speusis-badge-num").forEach(el => { el.style.color = t.textMuted; });
  root.querySelectorAll(".__speusis-badge-dl-btn").forEach(el => { el.style.background = t.bgDlBtn; });
  root.querySelectorAll(".__speusis-badge-type-tag").forEach(el => { el.style.background = t.tagBg; });

  if (menu) {
    menu.style.background = t.menuBg;
    menu.style.border = `1px solid ${t.menuBorder}`;
    menu.style.color = t.text;
    const slider = menu.querySelector(".__speusis-opacity-slider");
    if (slider) slider.style.background = t.sliderTrack;
    const darkBtn  = menu.querySelector("[data-theme='dark']");
    const lightBtn = menu.querySelector("[data-theme='light']");
    if (darkBtn) {
      darkBtn.style.background = theme === "dark" ? "rgba(60,80,200,0.25)" : "transparent";
      darkBtn.style.borderColor = theme === "dark" ? "rgba(100,130,255,0.5)" : t.border;
      darkBtn.style.color = t.text;
      darkBtn.classList.toggle("active", theme === "dark");
    }
    if (lightBtn) {
      lightBtn.style.background = theme === "light" ? "rgba(60,80,200,0.2)" : "transparent";
      lightBtn.style.borderColor = theme === "light" ? "rgba(80,110,220,0.5)" : t.border;
      lightBtn.style.color = t.text;
      lightBtn.classList.toggle("active", theme === "light");
    }
    const divider = menu.querySelector(".__speusis-divider");
    if (divider) divider.style.background = t.text;
    const menuLabel = menu.querySelectorAll(".__speusis-menu-label");
    menuLabel.forEach(l => { l.style.color = t.text; });
  }

  /* Store hover colors for JS-based hover effects */
  root._speusisTheme = { t, theme };
}

/* ── Render / update the badge ──────────────────────────────────── */
function updateStreamBadge() {
  if (detectedStreams.size === 0 || _badgeHidden) return;
  if (location.hostname.includes("youtube.com") && !isYouTubeVideoPage()) {
    hideBadge();
    return;
  }
  injectBadgeStyles();

  if (!streamBadgeEl) {
    streamBadgeEl = document.createElement("div");
    streamBadgeEl.id = "__speusis-stream-badge";

    /* Always mount outside YouTube's player DOM.  The player and its
     * fullscreen/controls layers frequently use overflow and stacking
     * contexts that clipped the old child badge. */
    document.documentElement.appendChild(streamBadgeEl);
  }
  applyBadgeVisibility();

  const title   = document.title.trim() || location.hostname;
  const rawStreams = [...detectedStreams.values()];
  const streams = dedupeYouTubeQualityStreams(rawStreams);

  const sendDl = (info) => {
    if (info.pending) return;
    if (info.needsMux) {
      sendRuntimeMessage({
        type: "speusis-download", needsMux: true,
        videoUrl: info.videoUrl, audioUrl: info.audioUrl,
        filename: sanitize(title) + ".mp4", isStream: true,
        pageTitle: title,
        fileSize: info.fileSize || null,
        streams: [{ ...info, url: info.videoUrl }],
      });
      return;
    }
    const ext = info.type === "Subtitle" ? ".vtt"
              : info.type === "HLS" ? ".m3u8" : info.type === "DASH" ? ".mpd" : ".ts";
    sendRuntimeMessage({
      type: "speusis-download", url: info.url,
      filename: sanitize(title) + ext, isStream: true,
      pageTitle: title,
      fileSize: info.fileSize || null,
      // Attach the actual detected stream (quality/type/url) instead of
      // leaving `streams` empty - an empty streams array made the dialog
      // fall back to its hardcoded "Best Quality / Medium Quality" HD/SD
      // placeholder even though a real stream had already been detected.
      streams: [info],
    });
  };

  const downloadAll = () => {
    streams.filter((info) => !info.pending).forEach(sendDl);
    if (streams.some((info) => !info.pending)) hideBadge();
  };
  const downloadOne = (info) => {
    sendDl(info);
    hideBadge();
  };

  const qualityRank = (info) => {
    const match = String(info.quality || "").match(/(\d{3,4})p/i);
    if (match) return Number(match[1]) * 10 + (/(60|50|48|30)\s*(?:fps)?/i.test(info.quality) ? 1 : 0);
    if (info.type === "Subtitle") return -2;
    if (info.type === "MP4") return 1;
    return 0;
  };
  const bestStream = [...streams].sort((a, b) => qualityRank(b) - qualityRank(a))[0];
  const downloadBest = () => {
    if (bestStream) downloadOne(bestStream);
  };

  const getLabel = (info, i) => {
    const fmt = info.type === "MP4" ? "MP4" : info.type === "HLS" ? "M3U8"
              : info.type === "DASH" ? "DASH" : info.type === "Subtitle" ? "Subtitle" : "Stream";
    const q   = info.quality || (["1080p HD","720p HD","480p","360p","240p","144p"][i] || `Q${i+1}`);
    const lock = info.encrypted ? " 🔒" : "";
    return `${sanitize(title).slice(0, 32)} — ${fmt}, ${q}${lock}`;
  };

  streamBadgeEl.classList.toggle("__speusis-collapsed", _badgeCollapsed);
  streamBadgeEl.innerHTML = `
    <div class="__speusis-badge-wrap">
      <div class="__speusis-badge-header">
        <button class="__speusis-drag-handle" id="__speusis-drag-handle" title="Drag panel" aria-label="Drag panel">⠿</button>
        <button class="__speusis-badge-main-btn" id="__speusis-main-dl-btn">
          <svg class="__speusis-badge-icon" viewBox="0 0 20 20" fill="none">
            <path d="M10 13.5L5.5 9h3V4h3v5h3L10 13.5z" fill="currentColor"/>
            <rect x="3.5" y="15.5" width="13" height="1.5" rx="0.75" fill="currentColor"/>
          </svg>
          Download this video
        </button>
        <button class="__speusis-collapse-btn" id="__speusis-collapse-btn"
                title="${_badgeCollapsed ? "Expand qualities" : "Collapse qualities"}"
                aria-label="${_badgeCollapsed ? "Expand qualities" : "Collapse qualities"}"
                aria-expanded="${!_badgeCollapsed}">
          <svg class="__speusis-collapse-icon" viewBox="0 0 16 16" fill="none" aria-hidden="true">
            <path d="M4.25 6.25 8 10l3.75-3.75" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </button>
        <button class="__speusis-badge-dots-btn" id="__speusis-dots-btn" title="Settings">⋮</button>
      </div>
      <div class="__speusis-badge-content">
        ${streams.length > 1 ? `<div class="__speusis-badge-download-all" id="__speusis-dl-all-btn">↓ Download all ${streams.length} streams</div>` : ""}
        <div class="__speusis-badge-list">
          ${streams.map((info, i) => `
            <div class="__speusis-badge-item" data-idx="${i}">
              <span class="__speusis-badge-num">${i+1}.</span>
              <span class="__speusis-badge-item-info" title="${info.url}">${getLabel(info, i)}</span>
              <span class="__speusis-badge-type-tag">${info.type}</span>
              <button class="__speusis-badge-dl-btn" data-idx="${i}">↓</button>
            </div>
          `).join("")}
        </div>
      </div>
      <div class="__speusis-collapsed-actions">
        <button class="__speusis-auto-btn" id="__speusis-auto-btn">↓ Auto download best quality</button>
      </div>
    </div>
    <div class="__speusis-settings-menu" id="__speusis-settings-menu">
      <div class="__speusis-menu-label">Theme</div>
      <div class="__speusis-theme-row">
        <button class="__speusis-theme-btn" data-theme="dark">🌙 Dark</button>
        <button class="__speusis-theme-btn" data-theme="light">☀️ Light</button>
      </div>
      <div class="__speusis-opacity-row">
        <div class="__speusis-menu-label">Opacity</div>
        <input class="__speusis-opacity-slider" type="range" min="30" max="100"
               value="${Math.round(_badgeOpacity * 100)}" step="2"/>
      </div>
      <div class="__speusis-divider"></div>
      <button class="__speusis-hide-btn" id="__speusis-hide-btn">Hide on this tab</button>
    </div>
  `;

  if (location.hostname.includes("youtube.com")) {
    requestAnimationFrame(positionBadgeOnYouTubePlayer);
  }
  wireBadgeDrag();

  /* Apply theme colors */
  applyTheme(streamBadgeEl, _badgeTheme, _badgeOpacity);

  /* ── Hover effects ── */
  const mainBtn = streamBadgeEl.querySelector("#__speusis-main-dl-btn");
  const t = themeVars(_badgeTheme, _badgeOpacity);
  if (mainBtn) {
    mainBtn.addEventListener("mouseenter", () => { mainBtn.style.background = t.mainBtnHov; });
    mainBtn.addEventListener("mouseleave", () => { mainBtn.style.background = "transparent"; });
    mainBtn.addEventListener("click", () => { streams.length === 1 ? downloadOne(streams[0]) : downloadAll(); });
  }

  const dlAllBtn = streamBadgeEl.querySelector("#__speusis-dl-all-btn");
  if (dlAllBtn) {
    dlAllBtn.addEventListener("mouseenter", () => { dlAllBtn.style.filter = "brightness(1.12)"; });
    dlAllBtn.addEventListener("mouseleave", () => { dlAllBtn.style.filter = ""; });
    dlAllBtn.addEventListener("click", downloadAll);
  }

  streamBadgeEl.querySelectorAll(".__speusis-badge-item").forEach(item => {
    item.addEventListener("mouseenter", () => { item.style.background = t.bgItem; });
    item.addEventListener("mouseleave", () => { item.style.background = "transparent"; });
    item.addEventListener("click", (e) => {
      if (e.target.classList.contains("__speusis-badge-dl-btn")) return;
      const idx = parseInt(item.dataset.idx);
      if (!isNaN(idx) && streams[idx]) downloadOne(streams[idx]);
    });
  });

  streamBadgeEl.querySelectorAll(".__speusis-badge-dl-btn").forEach(btn => {
    btn.addEventListener("mouseenter", () => { btn.style.background = t.bgDlBtnHov; });
    btn.addEventListener("mouseleave", () => { btn.style.background = t.bgDlBtn; });
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      const idx = parseInt(btn.dataset.idx);
      if (!isNaN(idx) && streams[idx]) downloadOne(streams[idx]);
    });
  });

  streamBadgeEl.querySelector("#__speusis-collapse-btn")?.addEventListener("click", (e) => {
    e.stopPropagation();
    _badgeCollapsed = !_badgeCollapsed;
    streamBadgeEl.classList.toggle("__speusis-collapsed", _badgeCollapsed);
    const btn = streamBadgeEl.querySelector("#__speusis-collapse-btn");
    if (btn) {
       const label = _badgeCollapsed ? "Expand qualities" : "Collapse qualities";
       btn.title = label;
       btn.setAttribute("aria-label", label);
       btn.setAttribute("aria-expanded", String(!_badgeCollapsed));
    }
  });
  streamBadgeEl.querySelector("#__speusis-auto-btn")?.addEventListener("click", (e) => {
    e.stopPropagation();
    downloadBest();
  });

  /* ── 3-dots settings menu ── */
  const dotsBtn    = streamBadgeEl.querySelector("#__speusis-dots-btn");
  const settingsMenu = streamBadgeEl.querySelector("#__speusis-settings-menu");

  dotsBtn?.addEventListener("click", (e) => {
    e.stopPropagation();
    if (settingsMenu) {
      /* Position the menu below the header dynamically */
      const header = streamBadgeEl.querySelector(".__speusis-badge-header");
      const headerH = header ? header.offsetHeight : 44;
      /* Also account for "download all" bar if present */
      const dlAllEl = streamBadgeEl.querySelector(".__speusis-badge-download-all");
      const dlAllH  = dlAllEl ? dlAllEl.offsetHeight : 0;
      settingsMenu.style.top = (headerH + dlAllH + 4) + "px";
      settingsMenu.classList.toggle("open");
    }
  });

  /* Close menu when clicking outside */
  document.addEventListener("click", function onDocClick(e) {
    if (!streamBadgeEl?.contains(e.target)) {
      settingsMenu?.classList.remove("open");
      document.removeEventListener("click", onDocClick);
    }
  });

  /* Theme buttons */
  settingsMenu?.querySelectorAll(".__speusis-theme-btn").forEach(btn => {
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      _badgeTheme = btn.dataset.theme;
      saveBadgeSettings();
      applyTheme(streamBadgeEl, _badgeTheme, _badgeOpacity);
    });
  });

  /* Opacity slider */
  const slider = settingsMenu?.querySelector(".__speusis-opacity-slider");
  slider?.addEventListener("input", (e) => {
    e.stopPropagation();
    _badgeOpacity = parseInt(e.target.value) / 100;
    saveBadgeSettings();
    applyTheme(streamBadgeEl, _badgeTheme, _badgeOpacity);
  });

  /* Hide button */
  streamBadgeEl.querySelector("#__speusis-hide-btn")?.addEventListener("click", (e) => {
    e.stopPropagation();
    _badgeHidden = true;
    hideBadge();
  });
}

function dedupeYouTubeQualityStreams(streams) {
  if (!location.hostname.includes("youtube.com")) return streams;
  const chosen = new Map();
  const result = [];
  for (const stream of streams) {
    if (stream.type !== "MP4" || !stream.quality) {
      result.push(stream);
      continue;
    }
    const match = String(stream.quality).match(/(\d{3,4}p)(?:\s+(\d+)\s*fps)?/i);
    const key = match
      ? `${match[1].toLowerCase()}-${match[2] || "default"}`
      : String(stream.quality).toLowerCase();
    const previous = chosen.get(key);
    if (!previous) {
      chosen.set(key, stream);
      result.push(stream);
      continue;
    }
    /* Prefer a direct progressive file over a mux request when both are
     * the same visible quality. Otherwise keep the first real URL. */
    if (previous.needsMux && !stream.needsMux) {
      const index = result.indexOf(previous);
      if (index >= 0) result[index] = stream;
      chosen.set(key, stream);
    }
  }
  return result;
}

function positionBadgeOnYouTubePlayer() {
  if (!streamBadgeEl || !isYouTubeVideoPage() || _badgeDragged) return;
  const player = document.querySelector("#movie_player, #player");
  if (!player) return;
  const rect = player.getBoundingClientRect();
  if (!rect.width || !rect.height) return;

  const margin = 8;
  const width = streamBadgeEl.offsetWidth || 310;
  const left = Math.max(8, Math.min(
    window.innerWidth - width - 8,
    rect.right - width - margin,
  ));
  const top = Math.max(8, Math.min(
    window.innerHeight - 48,
    rect.top + margin,
  ));
  streamBadgeEl.style.left = `${Math.round(left)}px`;
  streamBadgeEl.style.top = `${Math.round(top)}px`;
  streamBadgeEl.style.right = "auto";
}

function wireBadgeDrag() {
  const handle = streamBadgeEl?.querySelector("#__speusis-drag-handle");
  if (!handle || handle.__speusisDragWired) return;
  handle.__speusisDragWired = true;
  handle.addEventListener("pointerdown", (event) => {
    if (!streamBadgeEl) return;
    event.preventDefault();
    const rect = streamBadgeEl.getBoundingClientRect();
    const offsetX = event.clientX - rect.left;
    const offsetY = event.clientY - rect.top;
    handle.setPointerCapture?.(event.pointerId);
    const move = (moveEvent) => {
      if (!streamBadgeEl) return;
      _badgeDragged = true;
      const maxLeft = Math.max(8, window.innerWidth - streamBadgeEl.offsetWidth - 8);
      const maxTop = Math.max(8, window.innerHeight - streamBadgeEl.offsetHeight - 8);
      const left = Math.max(8, Math.min(maxLeft, moveEvent.clientX - offsetX));
      const top = Math.max(8, Math.min(maxTop, moveEvent.clientY - offsetY));
      streamBadgeEl.style.left = `${Math.round(left)}px`;
      streamBadgeEl.style.top = `${Math.round(top)}px`;
      streamBadgeEl.style.right = "auto";
    };
    const end = () => {
      handle.removeEventListener("pointermove", move);
      handle.removeEventListener("pointerup", end);
      handle.removeEventListener("pointercancel", end);
      handle.releasePointerCapture?.(event.pointerId);
    };
    handle.addEventListener("pointermove", move);
    handle.addEventListener("pointerup", end);
    handle.addEventListener("pointercancel", end);
  });
}

function hideBadge() {
  streamBadgeEl?.remove();
  streamBadgeEl = null;
}

/* ── YouTube: per-video hover-triggered badge (v0.26) ────────────────
 * Matches IDM's actual behavior, corrected from v0.25's overcorrection:
 * that version gated capture to /watch-page URLs only, which blocked
 * homepage thumbnail hover-previews entirely (those never become a real
 * /watch URL — they're an in-page expanding panel). Capture is URL-
 * unrestricted again; instead, whichever <video> element is currently
 * active (hovered thumbnail preview OR the real watch-page player) is
 * tracked directly. Every time that active element changes — a new
 * thumbnail hovered, or a real video navigated to — captured stream
 * state resets and hover show/hide re-attaches to the new element, so
 * the badge always reflects only the video currently under the mouse. */
let _ytHoverActive   = false; // kept for the hover-highlight effect only (see below), no longer gates visibility
let _ytHideTimer     = null;

function applyBadgeVisibility() {
  if (!streamBadgeEl) return;
  // v0.29: removed the hover-to-reveal gating added in v0.26. That was
  // never something you asked for as its own feature - it was me trying
  // to mimic "IDM only shows on hover," and it turned out to be the
  // actual root cause of every placement/disappearing bug since,
  // including the badge not showing at all. v0.21 never gated on hover
  // at all - it showed unconditionally the moment a stream was
  // detected, and that was the version that reliably showed something.
  // Back to that: always show once detected. The v0.28 positioning fix
  // (anchored to the real player instead of a viewport corner) stays -
  // that part was a genuine improvement, just never depended on hiding.
  streamBadgeEl.style.display = "";
}

function resetYouTubeCaptureState() {
  detectedStreams.clear();
  ytAdaptiveVideo.clear();
  ytAdaptiveAudio.clear();
  ytPendingFormats.clear();
  ytCurrentVideoId = "";
  ytKnownFormatCount = 0;
  ytLockedFormatCount = 0;
  _badgeDragged = false;
  // NOTE: deliberately does NOT touch _ytHoverActive. This runs from inside
  // the new video's own loadedmetadata handler, which fires shortly AFTER
  // mouseenter already set hoverActive=true for the thumbnail currently
  // under the mouse — resetting it here would immediately re-hide the
  // badge on every single hover despite the mouse never having left.
  hideBadge();
}

function attachYouTubeHoverTarget(media) {
  const target = media.closest("#movie_player") || media.parentElement || media;
  if (target.__speusisHoverAttached) return;
  target.__speusisHoverAttached = true;
  target.addEventListener("mouseenter", () => {
    clearTimeout(_ytHideTimer);
    _ytHoverActive = true;
    if (detectedStreams.size > 0) updateStreamBadge();
    applyBadgeVisibility();
  });
  target.addEventListener("mouseleave", () => {
    _ytHideTimer = setTimeout(() => { _ytHoverActive = false; applyBadgeVisibility(); }, 400);
  });
}

let _ytActiveVideoKey = "";
function handleYouTubeActiveVideo(media) {
  // v0.27 fix: attach the hover listener to ANY active-looking <video>
  // unconditionally, regardless of its src. YouTube plays virtually
  // everything - including homepage/grid hover-preview thumbnails, not
  // just the main watch-page player - through MediaSource Extensions,
  // meaning media.src/currentSrc is a blob: URL almost all the time.
  // The old code gated hover-attachment behind the same blob:/data:
  // exclusion used below for capture-state reset, which meant hover
  // previews (always blob:) rarely got the listener attached at all -
  // that was the actual cause of "download button doesn't show on
  // hover." Attaching the listener doesn't need a real URL, only the
  // DOM element; attachYouTubeHoverTarget() already no-ops on repeat
  // calls for the same element via its own __speusisHoverAttached flag.
  attachYouTubeHoverTarget(media);

  /* Do not clear the stream map from loadedmetadata. YouTube fires this
   * repeatedly while initializing MSE and when the player changes buffers;
   * the old reset made the panel appear briefly, then erase itself. The
   * yt-navigate-finish handler is the only navigation boundary that resets
   * a watch-page capture. */
  _ytActiveVideoKey = media.currentSrc || media.src || _ytActiveVideoKey;
}

function initYouTubePlayerHover() {
  if (!location.hostname.includes("youtube.com")) return;

  // Full navigation to a different video (real page swap via YouTube's SPA
  // router) is also a "new active video" — same reset, even before any
  // <video> loadedmetadata fires.
  let lastHref = location.href;
  document.addEventListener("yt-navigate-finish", () => {
    if (location.href === lastHref) return;
    lastHref = location.href;
    _ytActiveVideoKey = ""; // force the next loadedmetadata to re-attach/reset
    _ytHoverActive = false; // a real page navigation invalidates whatever was hovered before
    if (!isYouTubeVideoPage()) {
      _badgeHidden = false;
      resetYouTubeCaptureState();
      return;
    }

    /* yt-navigate-finish can fire after the new player's response has
     * already populated the list. Only reset when the URL proves this is a
     * different video; otherwise it erases the freshly detected formats. */
    const pageVideoId = getYouTubePageVideoId();
    if (pageVideoId && ytCurrentVideoId && pageVideoId !== ytCurrentVideoId) {
      resetYouTubeCaptureState();
    }
  });

  window.addEventListener("resize", positionBadgeOnYouTubePlayer, { passive: true });
  window.addEventListener("scroll", positionBadgeOnYouTubePlayer, { passive: true });
}

function getYouTubePageVideoId() {
  if (!location.hostname.includes("youtube.com")) return "";
  if (location.pathname.startsWith("/watch")) {
    return new URLSearchParams(location.search).get("v") || "";
  }
  const match = location.pathname.match(/^\/(?:shorts|live)\/([^/?]+)/);
  return match ? match[1] : "";
}

/* ── Video Grabber removed (v0.24) ────────────────────────────────
 * The per-<video> hover "Download" button used to live here, attached
 * to every <video>/<audio> element on any page (including YouTube's
 * homepage preview thumbnails) via a MutationObserver. Removed per
 * request — it was a second, easy-to-miss download surface duplicating
 * the main badge, and attaching to every media element on every page
 * (not just the one being watched) was more noise than signal. */

/* ── Intercept downloadable link clicks ─────────────────────────── */
document.addEventListener("click", (event) => {
  const link = event.target.closest?.("a[href]");
  if (!link) return;
  const href = link.href;
  if (!/^https?:\/\//i.test(href)) return;
  try {
    const pathname = new URL(href).pathname;
    if (!DOWNLOADABLE.test(pathname)) return;
  } catch { return; }

  event.preventDefault();
  event.stopPropagation();

  const filename = decodeURIComponent(href.split("/").filter(Boolean).pop()?.split("?")[0] || "");
  sendRuntimeMessage({ type: "speusis-download", url: href, filename: filename || undefined });
}, true);

/* ── Listen for MAIN-world network intercept messages ───────────── */
window.addEventListener("message", (e) => {
  if (e.source !== window || !e.data) return;

  if (e.data.__speusisYtFormats) {
    if (!isYouTubeVideoPage()) return;
    const formats = e.data.formats || [];
    const responseVideoId = String(e.data.videoId || "");
    if (responseVideoId && responseVideoId !== ytCurrentVideoId) {
      resetYouTubeCaptureState();
      ytCurrentVideoId = responseVideoId;
    }
    ytKnownFormatCount = formats.length;
    ytLockedFormatCount = formats.filter(f => f.locked).length;
    formats.forEach((f) => {
      if (!f.itag) return;
      const kind = f.hasVideo && f.hasAudio ? "combined" : f.hasVideo ? "video" : "audio";
      if (f.url) {
        if (f.hasVideo && !f.hasAudio) {
          ytPendingFormats.set(String(f.itag), {
            itag: String(f.itag),
            quality: f.quality || String(f.itag),
            type: "MP4",
            pending: true,
            kind: "video",
            timestamp: Date.now(),
          });
        } else {
          ytPendingFormats.delete(String(f.itag));
        }
      } else if (f.hasVideo) {
        ytPendingFormats.set(String(f.itag), {
          itag: String(f.itag),
          quality: f.quality || String(f.itag),
          type: "MP4",
          pending: true,
          kind,
          timestamp: Date.now(),
        });
      }
    });
    /* Plain URLs are already downloadable.  The previous code counted
     * them only for the hint and discarded them, which is why the panel
     * showed no quality ladder even when YouTube supplied usable URLs. */
    formats.filter(f => f.url && f.itag).forEach((f) => {
      recordYouTubeStream(
        f.url,
        String(f.itag),
        f.quality || String(f.itag),
        f.hasVideo && f.hasAudio ? "combined" : f.hasVideo ? "video" : "audio",
      );
    });
    updateStreamBadge();
    return;
  }
  if (e.data.__speusisYtCaptions) {
    (e.data.captions || []).forEach(recordYouTubeSubtitle);
    return;
  }
  if (e.data.__speusisYtLockedCipherData) {
    // Hand off to the service worker, which is the actual network caller
    // (see interceptor.js's v0.27 comment for why it's not called from
    // here directly). Best-effort - if this fails or the service worker
    // doesn't respond, formats simply stay locked, same as before.
    sendRuntimeMessage({
      type: "speusis-resolve-yt-cipher",
      playerUrl: e.data.playerUrl,
      formats: e.data.formats,
    }).catch(() => {});
    return;
  }
  if (e.data.__speusis) {
    if (location.hostname.includes("youtube.com") && !isYouTubeVideoPage()) {
      hideBadge();
      return;
    }
    if (e.data.isYouTube && e.data.ytItag) {
      recordYouTubeStream(e.data.url, e.data.ytItag, e.data.ytQuality || e.data.ytItag, e.data.ytKind, e.data.fileSize);
    } else {
      checkStreamUrl(e.data.url);
    }
    return;
  }
});

// v0.27: resolved results come back from the service worker (async,
// arrives well after the sendMessage call above returns) via the normal
// runtime message channel, not the window-level postMessage channel
// interceptor.js uses - the service worker isn't a page script.
chrome.runtime.onMessage.addListener((message) => {
  if (message?.type === "speusis-yt-cipher-resolved") {
    recordYouTubeStream(message.url, message.itag, message.quality, message.kind);
  }
});

/* ── Iframe awareness ──────────────────────────────────────────────
 * With "all_frames": true (added for cross-origin stream detection),
 * this whole script now also runs inside every iframe on the page,
 * not just the top document. A stream found inside a cross-origin
 * embed (Vimeo/Mux/Wistia-style players, ad-injected sources, etc.)
 * used to be completely invisible to detection before this. Rendering
 * the badge UI *inside* that iframe wouldn't work well - the iframe is
 * usually small and clipped - so subframes report up to the service
 * worker instead, which relays the detection to the page's top frame
 * to show in the one unified badge. Top-frame behavior (the common
 * case) is unchanged from before. */
const isTopFrame = window === window.top;

if (isTopFrame) {
  chrome.runtime.onMessage.addListener((message) => {
    if (message?.type === "speusis-subframe-stream-relay") {
      recordStream(message.url, message.streamType, message.encrypted);
    }
  });
}

/* ── AES-128 detection (detection only - decryption happens in the
 * desktop app's Rust downloader, not here) ────────────────────────── */
async function checkHlsEncryption(url) {
  try {
    const res = await fetch(url, { credentials: "include" });
    const text = await res.text();
    return /#EXT-X-KEY:METHOD=AES-128/i.test(text);
  } catch {
    return null; // unknown - CORS or network block, not necessarily unencrypted
  }
}

function checkStreamUrl(url, metadata) {
  if (!url || !url.startsWith("http")) return;
  try {
    const parsed = new URL(url);
    if (!STREAM_EXTS.test(parsed.pathname)) return;
    const type = detectStreamType(url);
    recordStream(url, type, undefined, metadata);
    if (type === "HLS") {
      checkHlsEncryption(url).then((encrypted) => {
        if (encrypted === null) return;
        markStreamEncrypted(url, encrypted);
      });
    }
  } catch {}
}

function detectStreamType(url) {
  if (/\.m3u8/i.test(url)) return "HLS";
  if (/\.mpd/i.test(url))  return "DASH";
  if (/\.m4s/i.test(url))  return "CMAF";
  return "Stream";
}

function recordStream(url, type, encrypted, metadata) {
  if (detectedStreams.has(url)) return;
  if (!isTopFrame) {
    // Report up instead of rendering a badge inside a (likely tiny,
    // clipped) cross-origin iframe. The top frame's listener above
    // relays this into its own detectedStreams / badge.
    detectedStreams.set(url, true); // dedupe guard for this frame only
    sendRuntimeMessage({
      type: "speusis-subframe-stream", url, streamType: type, encrypted,
    }).catch(() => {});
    return;
  }
  detectedStreams.set(url, { url, type, encrypted: encrypted ?? null, metadata: metadata || null, timestamp: Date.now() });
  updateStreamBadge();
}

function markStreamEncrypted(url, encrypted) {
  const info = detectedStreams.get(url);
  if (!info) return;
  info.encrypted = encrypted;
  if (isTopFrame) updateStreamBadge();
}

function recordYouTubeStream(url, itag, quality, kind, fileSize) {
  if (!isYouTubeVideoPage()) return;
  ytPendingFormats.delete(String(itag));
  if (kind === "video") {
    if (ytAdaptiveVideo.has(itag)) return;
    ytAdaptiveVideo.set(itag, { itag, quality, url, fileSize: fileSize || null });
    rebuildYouTubeMuxPairs();
    return;
  }
  if (kind === "audio") {
    if (ytAdaptiveAudio.has(itag)) return;
    ytAdaptiveAudio.set(itag, { itag, quality, url, fileSize: fileSize || null });
    rebuildYouTubeMuxPairs(); // an audio track just resolved — re-pair every known video itag
    return;
  }
  // "combined" (legacy progressive) or unspecified — original behavior.
  const key = `yt-itag-${itag}`;
  if (detectedStreams.has(key)) return;
  detectedStreams.set(key, { url, type: "MP4", quality, ytItag: itag, fileSize: fileSize || null, timestamp: Date.now() });
  updateStreamBadge();
}

/* Small color helper still used by the YouTube action-bar "Speusis" button
 * (the per-video hover overlay that used to share this was removed in v0.24). */
function videoOverlayStyle(theme) {
  const isDark = theme === "dark";
  return {
    bg:      isDark ? "rgba(10,12,24,0.82)"       : "rgba(240,242,255,0.88)",
    bgHov:   isDark ? "rgba(30,36,70,0.92)"       : "rgba(210,215,250,0.96)",
    color:   isDark ? "rgba(215,220,245,0.95)"    : "rgba(20,24,60,0.9)",
    border:  isDark ? "rgba(100,115,220,0.25)"    : "rgba(80,95,200,0.25)",
    shadow:  "0 4px 20px rgba(0,0,0,0.3), 0 1px 6px rgba(0,0,0,0.15)",
  };
}

/* ── YouTube Speusis button ───────────────────────────────────────── */
function initYouTubeGrabber() {
  if (!location.hostname.includes("youtube.com")) return;
  const tryInject = () => {
    if (!location.pathname.startsWith("/watch") || document.getElementById("__speusis-yt-btn")) return;
    const actions = document.querySelector("#top-level-buttons-computed, ytd-menu-renderer.ytd-video-primary-info-renderer");
    if (!actions) return;

    const btn = document.createElement("button");
    btn.id = "__speusis-yt-btn";
    btn.innerHTML = `<svg width="15" height="15" viewBox="0 0 20 20" fill="currentColor" style="vertical-align:middle;margin-right:6px;opacity:.85"><path d="M10 14L5 9h3.5V3h3V9H15L10 14z"/><rect x="3" y="16" width="14" height="2" rx="1"/></svg>Speusis`;
    Object.assign(btn.style, {
      display: "inline-flex", alignItems: "center", height: "36px", padding: "0 18px",
      border: "none", borderRadius: "18px",
      cursor: "pointer", fontSize: "14px", fontWeight: "600", marginLeft: "8px",
      fontFamily: "Segoe UI, system-ui, sans-serif",
      transition: "background 0.15s",
    });

    const s = videoOverlayStyle(_badgeTheme);
    Object.assign(btn.style, { background: s.bg, color: s.color, border: `1px solid ${s.border}`, backdropFilter: "blur(10px)", WebkitBackdropFilter: "blur(10px)" });
    btn.addEventListener("mouseenter", () => { btn.style.background = s.bgHov; });
    btn.addEventListener("mouseleave", () => { btn.style.background = s.bg; });
    btn.addEventListener("click", () => {
      const url = location.href;
      const title = document.querySelector("h1.ytd-watch-metadata yt-formatted-string, h1.title")?.textContent?.trim()
        || document.title.replace(" - YouTube", "").trim();
      const capturedStreams = [...detectedStreams.values()];
      sendRuntimeMessage({
        type: "speusis-download", url, filename: sanitize(title) + ".mp4",
        isYouTube: true, streams: capturedStreams, pageTitle: title,
      });
    });
    actions.appendChild(btn);
  };
  setTimeout(tryInject, 500);
  const ytObs = new MutationObserver(() => setTimeout(tryInject, 300));
  ytObs.observe(document.body, { childList: true, subtree: true });
}

/* ── Link Scanner ────────────────────────────────────────────────── */
chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  if (msg.type === "speusis-scan-links") {
    const links = [];
    const seen = new Set();
    const add = (url, name, kind = "link") => {
      if (!/^https?:\/\//i.test(url) || seen.has(url)) return;
      try {
        const pathname = new URL(url).pathname;
        if (!DOWNLOADABLE.test(pathname) && !STREAM_EXTS.test(pathname) && kind !== "media") return;
      } catch { return; }
      seen.add(url);
      links.push({ url, name: (name || url.split("/").pop()?.split("?")[0] || url).slice(0, 120), kind });
    };
    document.querySelectorAll("a[href]").forEach((a) => {
      const href = a.href;
      if (!/^https?:\/\//i.test(href)) return;
      try {
        const pathname = new URL(href).pathname;
        if (!DOWNLOADABLE.test(pathname) && !STREAM_EXTS.test(pathname)) return;
      } catch { return; }
      const name = a.textContent?.trim() || href.split("/").pop()?.split("?")[0] || href;
      add(href, name, "link");
    });
    document.querySelectorAll("video, audio, source, track, img").forEach((el) => {
      const src = el.currentSrc || el.src || el.href;
      if (!src || src.startsWith("blob:") || src.startsWith("data:")) return;
      const label = el.getAttribute("label") || el.getAttribute("title") ||
        document.title || src.split("/").pop()?.split("?")[0];
      add(src, label, el.tagName.toLowerCase() === "track" ? "subtitle" : "media");
    });
    for (const [, info] of detectedStreams) {
      if (info?.url) add(info.url, `[${info.type}] ${(info.url.split("/").pop() || info.url).slice(0, 90)}`, "stream");
    }
    sendResponse({ links });
    return true;
  }
  if (msg.type === "speusis-get-streams") {
    sendResponse({ streams: [...detectedStreams.values()] });
    return true;
  }
});

/* ── Helpers ────────────────────────────────────────────────────── */
function sanitize(str) {
  return (str || "video").replace(/[<>:"/\\|?*\x00-\x1f]/g, "").trim().slice(0, 120) || "video";
}

/* ── Media src watcher (invisible) ────────────────────────────────
 * Keeps feeding the main badge with plain <video src="direct.mp4">-style
 * URLs (sites with no HLS/DASH manifest, just a file directly on the
 * <video> tag) — this used to be a side effect of the hover-button code
 * removed above. No visible UI of its own; it only calls checkStreamUrl. */
function initMediaSrcWatcher() {
  const watch = (media) => {
    if (media.__speusisWatched) return;
    media.__speusisWatched = true;
    media.addEventListener("loadedmetadata", () => {
      if (location.hostname.includes("youtube.com")) handleYouTubeActiveVideo(media);
      const s = media.currentSrc;
      if (s && !s.startsWith("blob:") && !s.startsWith("data:")) {
        checkStreamUrl(s, {
          duration: Number.isFinite(media.duration) ? media.duration : null,
          width: media.videoWidth || null,
          height: media.videoHeight || null,
        });
      }
    });
  };
  document.querySelectorAll("video, audio").forEach(watch);
  if (videoObserver) videoObserver.disconnect();
  videoObserver = new MutationObserver((mutations) => {
    for (const mut of mutations) {
      for (const node of mut.addedNodes) {
        if (node.nodeType !== 1) continue;
        if (node.tagName === "VIDEO" || node.tagName === "AUDIO") watch(node);
        node.querySelectorAll?.("video, audio").forEach(watch);
      }
    }
  });
  videoObserver.observe(document.body, { childList: true, subtree: true });
}

/* ── Init ───────────────────────────────────────────────────────── */
function init() {
  initMediaSrcWatcher();
  initYouTubeGrabber();
  initYouTubePlayerHover();
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", init);
} else {
  init();
}
